name: Update movie listings

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 2,5"
      timezone: America/New_York

jobs:
  update-movies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Chromium and Playwright dependencies
        run: python -m playwright install --with-deps chromium

      - name: Update movie listings
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python moviegoer_v26.py
